export enum VALIDATORS {
  REQUIRED = 'REQUIRED',
  FORMAT = 'FORMAT',
  INCORRECT = 'INCORRECT',
  INVALID = 'INVALID',
  MIN_LENGTH = 'MIN_LENGTH',
  MAX_LENGTH = 'MAX_LENGTH',
  LENGTH = 'LENGTH',
  CORRUPT = 'CORRUPT'
}
